version: 2.1

orbs:
#  android: circleci/android@0.2.0
  docker: circleci/docker@0.5.17

jobs:
  build:
    docker: 
      - image: circleci/openjdk:11.0.3-jdk-stretch
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      GRADLE_HOME: /opt/gradle-5.5.1
    steps:
      - checkout
      - setup_remote_docker:   
          docker_layer_caching: true 
      - run:
          name: Check Gradle Version
          command: |
            gradle -v # Gradle 5.5.1
      - run:
          name: Create gradle.properties
          command: |
            echo 'export GRADLE_PROPERTIES=${HOME}/.gradle/gradle.properties' >> $BASH_ENV
            # echo "export bintray_api_key=$bintray_api_key" > $BASH_ENV
            # echo "export bintray_user=$bintray_user" >> $BASH_ENV
            echo "export KEYSTORE_PATH=circleci.keystore" >> $BASH_ENV
            echo "export KEYSTORE_PASS=circleci" >> $BASH_ENV
            echo "export ALIAS=jkg" >> $BASH_ENV
            echo "export ALIAS_PASS=circleci" >> $BASH_ENV
            # echo "export SEGMENT_DEBUG_KEY=$segment_key" >> $BASH_ENV
            # echo "export SENTRY_DSN=$sentry_dsn" >> $BASH_ENV
            # echo "export SEGMENT_WRITE_KEY=$sentry_write_key" >> $BASH_ENV
            # echo "export SENTRY_DEBUG_DSN=$SENTRY_DEBUG_DSN" >> $BASH_ENV
            # echo "export SENTRY_PROD_DSN=$SENTRY_PROD_DSN" >> $BASH_ENV
            # echo "export BC_LOCAL_HOST=$BC_LOCAL_HOST" >> $BASH_ENV
            # echo "export BC_LOCAL_DOMAIN=$BC_LOCAL_DOMAIN" >> $BASH_ENV
            # echo "export BC_INTEGRATION_HOST=$BC_INTEGRATION_HOST" >> $BASH_ENV
            # echo "export BC_INTEGRATION_DOMAIN=$BC_INTEGRATION_DOMAIN" >> $BASH_ENV
            # echo "export BC_STAGING_HOST=$BC_STAGING_HOST" >> $BASH_ENV
            # echo "export BC_STAGING_DOMAIN=$BC_STAGING_DOMAIN" >> $BASH_ENV
            # echo "export BC_PRODUCTION_HOST=$BC_PRODUCTION_HOST" >> $BASH_ENV
            # echo "export BC_PRODUCTION_DOMAIN=$BC_PRODUCTION_DOMAIN" >> $BASH_ENV
            # echo "export GOOGLE_MAPS_API_KEY_DEBUG=$GOOGLE_MAPS_API_KEY_DEBUG" >> $BASH_ENV
            # echo "export GOOGLE_MAPS_API_KEY_PROD=$GOOGLE_MAPS_API_KEY_PROD" >> $BASH_ENV
            echo "export TEST_API_ACCESS_TOKEN=null" >> $BASH_ENV
            echo "export TEST_API_CLIENT_ID=null" >> $BASH_ENV
            echo "export org.gradle.caching=true" >> $BASH_ENV
            source $BASH_ENV
      - run: 
          name: Create fresh keystore file 
          command: | # https://circleci.com/docs/2.0/contexts/#restrict-a-context-to-a-security-group-or-groups
            rm -f circleci.keystore
            printf '\n\n\n\n\n\nyes\n' | keytool -genkey -v -keystore circleci.keystore -storepass circleci -alias jkg -keyalg RSA -keysize 2048 -validity 10000
      - run:
          name: Run Gradle Wrapper
          command: | 
            gradle wrapper

# cd ${HOME}
# cd ..
# cd /opt
# ls
# apache-ant	   apache-maven        gradle	     sbt
# apache-ant-1.10.6  apache-maven-3.6.1  gradle-5.5.1
# CircleCI received exit code 0


# $GRADLE_HOME/bin/gradle -v
# /bin/bash: /opt/gradle/gradle-5.5.1/bin/gradle: No such file or directory

workflows:
  build:
    jobs:
      - build 