version: 2.1

orbs:
#  android: circleci/android@0.2.0
  docker: circleci/docker@0.5.17

jobs:
  build:
    docker: 
      - image: circleci/openjdk:11.0.3-jdk-stretch
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      GRADLE_HOME: /opt/gradle/gradle-6.0.0
    steps:
      - checkout
      - setup_remote_docker:   
          docker_layer_caching: true 
      - run:
          name: Setup Gradle
          command: |
            cd ${HOME}/opt/gradle
            ls
            ${GRADLE_HOME}/bin/gradle -v
            ls ${GRADLE_HOME}
            
workflows:
  build:
    jobs:
      - build 