version: 2.1

orbs:
#  android: circleci/android@0.2.0
  docker: circleci/docker@0.5.17

jobs:
  build:
    docker: 
      - image: circleci/openjdk:11.0.3-jdk-stretch
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      GRADLE_HOME: /opt/gradle-5.5.1
    steps:
      - checkout
      - setup_remote_docker:   
          docker_layer_caching: true 
      - run:
          name: Check Gradle Version
          command: |
            gradle -v # Gradle 5.5.1
      - run:
          name: Create gradle.properties
          command: |
            echo 'export GRADLE_PROPERTIES=${HOME}/.gradle/gradle.properties' >> $BASH_ENV
            source $BASH_ENV
            echo "gradle.properties should exist at ${GRADLE_PROPERTIES}"
      - run: 
          name: Create fresh keystore file
          command: | # https://circleci.com/docs/2.0/contexts/#restrict-a-context-to-a-security-group-or-groups
            rm -f circleci.keystore
            printf '\n\n\n\n\n\nyes\n' | keytool -genkey -v -keystore circleci.keystore -storepass cci -alias jkg -keyalg RSA -keysize 2048 -validity 10000
            

# cd ${HOME}
# cd ..
# cd /opt
# ls
# apache-ant	   apache-maven        gradle	     sbt
# apache-ant-1.10.6  apache-maven-3.6.1  gradle-5.5.1
# CircleCI received exit code 0


# $GRADLE_HOME/bin/gradle -v
# /bin/bash: /opt/gradle/gradle-5.5.1/bin/gradle: No such file or directory

workflows:
  build:
    jobs:
      - build 